core/urls.py
from django.urls import include, path
from .views import *
from rest_framework import routers

#URL APIS
router = routers.DefaultRouter()
router.register('artista', ArtistaViewSet)
router.register('producto', ProductoViewSet)

urlpatterns = [
    path('', index, name="index"),
    path('accounts/register/', register, name="register"),
    path('productos/', products, name="productos"),
    path('galeria/', gallery, name="galeria"),
    path('acerca/', about, name="acerca"),
    path('carrito/', carrito, name="carrito"),
    path('carrito/add/<int:producto_id>/', agregar_producto_carrito, name="carritoadd"),
    path('carrito/contadordeproductos/', cantidad_productos_carrito, name="carritocontador"),
    path('carrito/delete/<int:producto_id>/', eliminar_producto_carrito, name="carritodelete"),
    path('limpiar_carrito/', limpiar_carrito, name='limpiar_carrito'),
    path('compras/', historialcompra, name="historial_compra"),
    path('registrar_compra/', registrar_compra, name="registrar_compra"),
    path('generar_voucher/<int:compra_id>/', generar_voucher, name='generar_voucher'),
    path('miembros/', miembros, name="miembros"),
    path('artista/<int:artista_id>/', artista, name="artista"),
    path('solicitud/productos/', solicitudP, name="solicitudP"),
    path('solicitud/artista/', solicitudA, name="solicitudA"),
    path('solicitud/editar-p/<int:solicitud_id>/', editar_solicitud_p, name="editar_solicitud-p"),
    path('solicitud/editar-a/<int:solicitud_id>/', editar_solicitud_a, name="editar_solicitud-a"),
    path('administradores/', listar_para_administradores, name="administradores"),
    path('administradores/solicitudes/', administradores, name="solicitudes_admin"),
    path('administradores/agregar-artista/', agregar_artista, name="agregar_artista"),
    path('administradores/agregar-producto/', agregar_producto, name="agregar_producto"),
    path('administradores/agregar-miembro/', agregar_miembro, name="agregar_miembro"),
    path('administradores/rechazar-a/<int:solicitud_id>/', rechazar_solicitud_a, name="rechazar_solicitud-a"),
    path('administradores/rechazar-p/<int:solicitud_id>/', rechazar_solicitud_p, name="rechazar_solicitud-p"),
    path('administradores/aprobar-a/<int:solicitud_id>/', aprobar_solicitud_a, name="aprobar_solicitud-a"),
    path('administradores/aprobar-p/<int:solicitud_id>/', aprobar_solicitud_p, name="aprobar_solicitud-p"),
    path('administradores/editar-a/<int:artista_id>/', editar_artista, name="editar_artista"),
    path('administradores/quitarimg-a/<int:artista_id>/', quitar_imagen_artista, name="quitar_img_artista"),
    path('administradores/editar-p/<int:producto_id>/', editar_producto, name="editar_producto"),
    path('administradores/editar-m/<int:miembro_id>/', editar_miembro, name="editar_miembro"),
    path('administradores/eliminar-a/<int:artista_id>/', eliminar_artista, name="eliminar_artista"),
    path('administradores/eliminar-p/<int:producto_id>/', eliminar_producto, name="eliminar_producto"),
    path('administradores/eliminar-m/<int:miembro_id>/', eliminar_miembro, name="eliminar_miembro"),
    path('administradores/enable_or_disable_artista/<int:artista_id>/', enable_or_disable_artista, name="enable_or_disable_artista"),
    path('administradores/enable_or_disable_producto/<int:producto_id>/', enable_or_disable_producto, name="enable_or_disable_producto"),
    path('administradores/enable_or_disable_miembro/<int:miembro_id>/', enable_or_disable_miembro, name="enable_or_disable_miembro"),
    #APIS
    path('api/', include(router.urls)),
    #API LAST_FM
    path('lastfm_api/', lastfm_api, name="lastfm_api"),
    #ACCOUNT LOCKED
    path('locked/', locked, name="locked"),
]

musica/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('captcha/',include('captcha.urls')),
    path('password_reset/', 
        auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),
        name='password_reset'),
    path('password_reset/done/', 
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset/done/', 
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.utils import timezone
import os
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission, BaseUserManager
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import re

def upload_to_artista(instance, filename):
    # Eliminar caracteres especiales del nombre del artista
    nombre_limpio = re.sub(r'\W+', '', instance.nombre, flags=re.UNICODE)
    return f'artistas/{nombre_limpio}/{filename}'

def upload_to_producto(instance, filename):
    # Eliminar caracteres especiales del nombre del artista y del título del producto
    nombre_limpio = re.sub(r'\W+', '', instance.artista.nombre, flags=re.UNICODE)
    titulo_limpio = re.sub(r'\W+', '', instance.titulo, flags=re.UNICODE)
    return f'productos/{nombre_limpio}/{titulo_limpio}/{filename}'

def upload_to_temp(instance, filename):
    # Determinar el tipo de solicitud y el ID
    if isinstance(instance, SolicitudP):
        tipo_solicitud = 'P'
    elif isinstance(instance, SolicitudA):
        tipo_solicitud = 'A'
    else:
        raise ValueError("Tipo de instancia de solicitud desconocido.")

    if instance.pk:
        solicitud_id = instance.pk
    else:
        solicitud_id = 'TEMP'

    return f'temp/solicitudes/{instance.usuario.username}/{tipo_solicitud}/{solicitud_id}/{filename}'

class Artista(models.Model):
    nombre = models.CharField(max_length=50)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    biografia = models.TextField(null=True, blank=True)
    imagen = models.ImageField(upload_to=upload_to_artista, null=True, blank=True, max_length=255)
    sitio_web = models.URLField(null=True, blank=True)
    habilitado = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre
    def biografia_breve(self):
        return ' '.join(self.biografia.split('.')[:2]) + '.'
    def nombreimagen(self):
        return os.path.basename(self.imagen.name)

class TipoProducto(models.Model):
    TIPO_CHOICES = [
        ('cancion', 'Canción'),
        ('album', 'Álbum'),
        ('ep', 'EP'),
    ]

    nom_tipo = models.CharField(max_length=20, choices=TIPO_CHOICES)

    def __str__(self):
        return dict(self.TIPO_CHOICES)[self.nom_tipo]

class Producto(models.Model):
    titulo = models.CharField(max_length=80)
    descripcion = models.TextField(null=False, blank=False)
    imagen = models.ImageField(upload_to=upload_to_producto, blank=False, null=False, max_length=255)
    artista = models.ForeignKey(Artista, on_delete=models.CASCADE)
    tipo = models.ForeignKey(TipoProducto, on_delete=models.CASCADE)
    precio = models.IntegerField(default=0)
    habilitado = models.BooleanField(default=True)

    def __str__(self):
        return self.titulo

    def descripcion_breve(self):
        # Elimina los puntos al inicio del texto
        descripcion = self.descripcion.lstrip('.')
        # Divide el texto en frases
        frases = [frase for frase in descripcion.split('.') if frase]
        # Une las dos primeras frases
        return ' '.join(frases[:2]) + '.'

    def precio_clp(self):
        return "${:,.0f}".format(self.precio).replace(",", ".")
    
    def nombreimagen(self):
        return os.path.basename(self.imagen.name)
    
    def obtener_descripcion_formateada(self):
        # Aquí realizas cualquier formateo necesario
        # Por ejemplo, reemplazando '\n' con '<br>' para saltos de línea
        return self.descripcion.replace('\n', '<br>')
    
class TipoUsuario(models.Model):
    TIPO_CHOICES = [
        ('comun', 'Común'),
        ('miembro', 'Miembro'),
        ('admin', 'Admin'),
    ]
    nom_tipo = models.CharField(max_length=20, choices=TIPO_CHOICES)

    def __str__(self):
        return self.nom_tipo

class UsuarioManager(BaseUserManager):
    def create_user(self, username, email, password=None, tipo_usuario=None, **extra_fields):
        if not username:
            raise ValueError('The Username field must be set')
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(username=username, email=email, tipo_usuario=tipo_usuario, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, username, email, password=None, tipo_usuario=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        tipo_usuario, created = TipoUsuario.objects.get_or_create(nom_tipo='admin')

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        if tipo_usuario is None:
            raise ValueError('Superuser must have a tipo_usuario.')

        extra_fields['tipo_usuario'] = tipo_usuario

        return self.create_user(username, email, password, **extra_fields)
    
class Usuario(AbstractUser):
    email = models.EmailField(_('email address'), unique=True, blank=False, null=False)
    tipo_usuario = models.ForeignKey(TipoUsuario, on_delete=models.CASCADE)

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    groups = models.ManyToManyField(
        Group,
        verbose_name=_('groups'),
        blank=True,
        help_text=_(
            'The groups this user belongs to. A user will get all permissions '
            'granted to each of their groups.'
        ),
        related_name="core_usuario_groups",
        related_query_name="user",
    )

    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name=_('user permissions'),
        blank=True,
        help_text=_('Specific permissions for this user.'),
        related_name="core_usuario_user_permissions",
        related_query_name="user",
    )

    objects = UsuarioManager()

    def save(self, *args, **kwargs):
        if self.pk is None:
            if not self.password.startswith('pbkdf2_sha256$'):
                self.set_password(self.password)
        else:
            original_usuario = Usuario.objects.get(pk=self.pk)
            if self.password != original_usuario.password:
                if not self.password.startswith('pbkdf2_sha256$'):
                    self.set_password(self.password)
        super(Usuario, self).save(*args, **kwargs)

    def __str__(self):
        return self.username
    
class SolicitudP(models.Model):
    ESTADO_CHOICES = [
        ('E', 'En Espera'),
        ('A', 'Aprobado'),
        ('R', 'Rechazado'),
    ]
    
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    estado = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='E')
    nombre_producto = models.CharField(max_length=100)
    descripcion_producto = models.TextField()
    imagen_producto = models.ImageField(blank=False, null=False, upload_to=upload_to_temp, max_length=255)
    artista_producto = models.ForeignKey(Artista, on_delete=models.CASCADE, default=None)
    tipo_producto = models.CharField(max_length=20, choices=TipoProducto.TIPO_CHOICES)
    precio_producto = models.IntegerField(default=0)

    def __str__(self):
        return f"Solicitud #{self.pk} de {self.usuario.username} - {self.tipo_producto}: {self.nombre_producto}"
    
class SolicitudA(models.Model):
    ESTADO_CHOICES = [
        ('E', 'En Espera'),
        ('A', 'Aprobado'),
        ('R', 'Rechazado'),
    ]
    
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    estado = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='E')
    nombre_artista = models.CharField(max_length=50)
    fecha_nacimiento_artista = models.DateField(null=True, blank=True)
    biografia_artista = models.TextField(null=True, blank=True)
    imagen_artista = models.ImageField(null=True, blank=True, upload_to=upload_to_temp, max_length=255)
    sitio_web_artista = models.URLField(null=True, blank=True)

    def __str__(self):
        return f"Solicitud #{self.pk} de {self.usuario.username} - Artista: {self.nombre_artista}"

class SolicitudesRechazadas(models.Model):
    solicitudA = models.ForeignKey(SolicitudA, on_delete=models.CASCADE, null=True, blank=True)
    solicitudP = models.ForeignKey(SolicitudP, on_delete=models.CASCADE, null=True, blank=True)
    mensaje_rechazo = models.TextField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.solicitudA and self.solicitudP:
            raise ValidationError("Una solicitud rechazada no puede estar relacionada con ambas solicitudes (SolicitudA y SolicitudP) al mismo tiempo.")
        super().save(*args, **kwargs)

    def __str__(self):
        if self.solicitudA:
            return f"Rechazo #{self.pk} - SolicitudA #{self.solicitudA.pk}"
        elif self.solicitudP:
            return f"Rechazo #{self.pk} - SolicitudP #{self.solicitudP.pk}"
        else:
            return f"Rechazo #{self.pk} - Sin solicitud relacionada"
    

class Carrito(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)

class historial_compra(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    fecha_compra = models.DateField(default=timezone.now)
    metodo_pago = models.CharField(max_length=20)
    total_clp = models.CharField(max_length=10)
    total_usd = models.CharField(max_length=10)
    productos = models.ManyToManyField(Producto)
    cantidades_productos = models.JSONField(default=dict)

    def str(self):
        return f"Pago de {self.usuario.username} el {self.fecha_compra}"

core/templates/core/miembros/crud/updateA.html
{% extends "core/base.html" %}

{% load static %}

{% block titulo %}<title>Grupo Cero - Actualizar solicitud</title>{% endblock %}

{% block navmenuver %}{% endblock %}

{% block navbuscar %}{% endblock %}

{% block navmenu %}{% endblock %}

{% block navcarrito %}{% endblock %}

{% block contenido %}
<div class="container">
    <div class="row text-center justify-content-center">
        <div class="col-md-6">
            <a href="{% url 'miembros' %}" class="btn btn-secondary mb-3"><i class="bi bi-arrow-left"></i> Volver al panel de miembros</a>
            <div class="container my-5">
                {% load crispy_forms_tags %}
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'imagen_artista' %}
                            {{ field|as_crispy_field }}
                        {% else %}
                            <p>Imágen Artista</p>
                            {% if field.value %}
                                <img id="preview" src="{{ field.value.url }}" alt="Imagen del artista" class="my-5" style="max-width: 50%;">
                            {% else %}
                                <img id="preview" src="#" alt="Imagen del artista" class="my-5" style="max-width: 50%; display: none;">
                            {% endif %}
                            <input type="file" name="{{ field.name }}" id="id_imagen_artista">
                        {% endif %}
                    {% endfor %}
                    <input class="btn btn-success my-5" type="submit" value="Actualizar">
                </form>
                {{ msj }}
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById('id_imagen_artista').onchange = function (event) {
        var reader = new FileReader();
        reader.onload = function(){
            var output = document.getElementById('preview');
            output.src = reader.result;
            output.style.display = 'block';
        };
        reader.readAsDataURL(event.target.files[0]);
    };
    </script>
{% endblock %}

{% block modals %}
{% endblock %}

{% block customfooter %}
{% endblock %}

core/templates/core/miembros/crud/updateP.html
{% extends "core/base.html" %}

{% load static %}

{% block titulo %}<title>Grupo Cero - Actualizar solicitud</title>{% endblock %}

{% block navmenuver %}{% endblock %}

{% block navbuscar %}{% endblock %}

{% block navmenu %}{% endblock %}

{% block navcarrito %}{% endblock %}

{% block contenido %}
<div class="container">
    <div class="row text-center justify-content-center">
        <div class="col-md-6">
            <a href="{% url 'miembros' %}" class="btn btn-secondary mb-3"><i class="bi bi-arrow-left"></i> Volver al panel de miembros</a>
            <div class="container my-5">
                {% load crispy_forms_tags %}
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'imagen_producto' %}
                            {{ field|as_crispy_field }}
                        {% else %}
                            <p>Imágen Producto</p>
                            {% if field.value %}
                                <img id="preview" src="{{ field.value.url }}" alt="Imagen del producto" class="my-5" style="max-width: 50%;">
                            {% else %}
                                <img id="preview" src="#" alt="Imagen del producto" class="my-5" style="max-width: 50%; display: none;">
                            {% endif %}
                            <input type="file" name="{{ field.name }}" id="id_imagen_producto">
                        {% endif %}
                    {% endfor %}
                    <input class="btn btn-success my-5" type="submit" value="Actualizar">
                </form>
                {{ msj }}
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById('id_imagen_producto').onchange = function (event) {
        var reader = new FileReader();
        reader.onload = function(){
            var output = document.getElementById('preview');
            output.src = reader.result;
            output.style.display = 'block';
        };
        reader.readAsDataURL(event.target.files[0]);
    };
    </script>
{% endblock %}

{% block modals %}
{% endblock %}

{% block customfooter %}
{% endblock %}